### ISSUE TITLE
部分章节转换失败

### ISSUE THREAD

**Issue by yhxkry** [zhongfly/view2webp#1]
您好。我试着对B漫里的《汤神君没有朋友》使用您的程序，在B漫里应该一共有81个章节，但是经过程序转换后69章以后的章节没有转换成功，依然是6位数字的文件夹。

我看转换失败的文件夹里面的基本都是.jpg.view，也有index文件。还有一个文件夹里只有1.webp和index.dat，文件名依然是6位数字。
![微信截图_20191223162314](https://user-images.githubusercontent.com/52891100/71345783-378a6300-25a1-11ea-94fd-4f33d0b7841c.png)
![微信截图_20191223162821](https://user-images.githubusercontent.com/52891100/71345802-453fe880-25a1-11ea-9e2e-f0d9c17cebce.png)
![微信截图_20191223162853](https://user-images.githubusercontent.com/52891100/71345820-51c44100-25a1-11ea-83ea-e56661b62e54.png)

另外，还想问一个：我在github上还看到有别的提取B漫的工具，它貌似是提取网页端的原图，提取的是jpeg格式的图，图片大小比这个工具提取的webp大很多。请问是否清楚两者清晰度有无差别？哪个比较好？

**Comment by zhongfly** [comment]
个人测试 第80话转换正常
webp与jpeg主要是格式不同，放大200%时我肉眼没有发现明显区别。
左为webp，右为jpg（[提取工具](https://github.com/zhongfly/bilibilicomic) ）
![对比图](https://i.loli.net/2020/01/24/s7wL1FXlacNyver.png)

**Comment by tuty-tyty** [comment]
您好 今天我转换青春retry和其他一部漫画失败了
仅仅是里面的文件夹改名了

**Comment by zhongfly** [comment]
文件夹禁止改名，会导致自动重命名失败

tuty-tyty <notifications@github.com> 于 2020年3月4日周三 05:30写道：

**Comment by tuty-tyty** [comment]
是这样的，我没有去主动改文件夹名
只是，转换前的图片后缀不再是.jpg.view 而是.png.view
无法被转换成webp

**Comment by zhongfly** [comment]
你自己批量重命名一下改成jpg.view是一样的。我之前已经试过png.view没问题，只是后缀看起来不同罢了。代码里懒得把png.view后缀的包括在内而已

tuty-tyty <notifications@github.com> 于 2020年3月4日周三 22:50写道：
